/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DialogEngine.framework/DialogEngine
 */

@interface DialogEngineContext : NSObject {
    NSString * siriLocale;
}

@property (nonatomic, retain) NSString *siriLocale;

- (void).cxx_destruct;
- (id)init;
- (void)setSiriLocale:(id)arg1;
- (id)siriLocale;

@end
