/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthVisualization.framework/HealthVisualization
 */

@interface HealthVisualization.DateDistributionCalculator : _TtCs12_SwiftObject {
    void configuration;
    void variant;
}

@end
