/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthVisualization.framework/HealthVisualization
 */

@interface HealthVisualization.OnlineInsightService : _TtCs12_SwiftObject {
    void healthStore;
    void operationQueue;
    void requests;
}

@end
