/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamKit.framework/ShazamKit
 */

@interface SHConfiguration : NSObject

@property (nonatomic, readonly) double maximumSignatureLength;
@property (nonatomic, readonly) double minimumSignatureLength;

- (id)deviceModel;
- (id)deviceSystemName;
- (id)deviceSystemVersion;
- (id)frameworkShortVersion;
- (double)maximumSignatureLength;
- (double)minimumSignatureLength;

@end
