/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamKit.framework/ShazamKit
 */

@interface SHPartnerAPISyncedLyricsParser : NSObject

+ (id)syncedLyricsFromDictionary:(id)arg1;

@end
