/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FormatLayoutViewRenderer : _TtCs12_SwiftObject {
    void behaviorRenderer;
    void buttonNodeRenderer;
    void imageNodeRenderer;
    void presentingViewController;
    void rendererTool;
    void textNodeRenderer;
    void traitCollection;
    void viewNodeRenderer;
    void webEmbedNodeRenderer;
    void webEmbedViewControllerReuseManager;
}

@end
