/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FeedLayoutAttributesFactoryProvider : _TtCs12_SwiftObject {
    void issueCoverViewLayoutAttributesFactory;
}

@end
