/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.CoverIssueViewRenderer : _TtCs12_SwiftObject {
    void issueCoverViewRenderer;
    void rendererTool;
    void traitCollection;
}

@end
