/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.HeadlineService : _TtCs12_SwiftObject {
    void contentContext;
    void coreConfigurationManager;
    void paidAccessChecker;
    void tagService;
}

@end
