/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FollowingManager : _TtCs12_SwiftObject {
    void alertPresenter;
    void notificationManager;
    void subscriptionController;
}

@end
