/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.WebEmbedViewController : UIViewController <NEURLHandlerDelegate> {
    void activityIndicator;
    void configurationManager;
    void configurationProvider;
    void contentFrame;
    void debugButton;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  embedURL;
    void errorProvider;
    void errorState;
    void errorView;
    void interactionProvider;
    void onReuse;
    void presentationManager;
    void reuseIdentifier;
    void stateMachine;
    void tapGestureRecognizer;
    void webContentViewController;
    void webLinkPresentingViewController;
}

- (void).cxx_destruct;
- (void)URLHandler:(id)arg1 wantsToPresentViewController:(id)arg2 animated:(bool)arg3;
- (void)handleTapWithRecognizer:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

@end
