/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.CoverChannelViewRenderer : _TtCs12_SwiftObject {
    void imageCache;
    void rendererTool;
    void traitCollection;
}

@end
