/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FormatTextNodeRenderer : _TtCs12_SwiftObject {
    void traitCollection;
}

@end
