/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AutomaticAssessmentConfiguration.framework/AutomaticAssessmentConfiguration
 */

@interface AEAssessmentConfiguration : NSObject <NSCopying>

- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
