/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TrackingAvoidance.framework/TrackingAvoidance
 */

@interface TAFilterSuspiciousDeviceUpdate : NSObject

+ (id)filterSuspiciousDeviceWithStore:(id)arg1 lastFilterDate:(id)arg2;

@end
