/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NewsSubscription.PaywallApplicationStateMonitor : _TtCs12_SwiftObject {
    void eventHandler;
}

@end
