/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NewsSubscription.PaywallEventHandler : _TtCs12_SwiftObject {
    void coordinator;
    void delegate;
    void interactor;
    void router;
}

@end
