/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NewsSubscription.SoftPaywallStyler : _TtCs12_SwiftObject {
    void colorPaletteProvider;
    void descriptionMaxLines;
    void titleMaxLines;
}

@end
