/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NewsSubscription.HardPaywallRenderer : _TtCs12_SwiftObject {
    void styler;
}

@end
