/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsSubscription.framework/NewsSubscription
 */

@interface NewsSubscription.ArticlePaywallTypeProvider : _TtCs12_SwiftObject {
    void articleSoftPaywallMeter;
    void bundleSubscriptionManager;
    void configurationManager;
    void paidAccessChecker;
    void subscriptionAccessMeter;
}

@end
