/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FMNetworking.framework/FMNetworking
 */

@interface FMNetworking.FMNServerInteractionController : _TtCs12_SwiftObject {
    void authenticationProvider;
    void mockingPreferences;
    void urlSessionFactory;
}

@end
