/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthRecordsUI.framework/HealthRecordsUI
 */

@interface HealthRecordsUI.AccountErrorManager : _TtCs12_SwiftObject {
    void healthRecordsStore;
    void profile;
}

@end
