/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthRecordsUI.framework/HealthRecordsUI
 */

@interface HRInternalStateItem : NSObject {
    void title;
    void value;
}

- (void).cxx_destruct;
- (id)init;

@end
