/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthRecordsUI.framework/HealthRecordsUI
 */

@interface HRInternalStateSection : NSObject {
    void items;
    void title;
}

- (void).cxx_destruct;
- (id)init;

@end
