/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKEmergencyCardFooterTableItem : HKEmergencyCardTableItem {
    NSAttributedString * _attributedTitleForFooter;
    HKEmergencyCardFooterCell * _cell;
}

@property (nonatomic, retain) NSAttributedString *attributedTitleForFooter;

- (void).cxx_destruct;
- (id)_cell;
- (id)attributedTitleForFooter;
- (bool)hasPresentableData;
- (id)initInEditMode:(bool)arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })separatorInset;
- (void)setAttributedTitleForFooter:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndex:(long long)arg2;

@end
