/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKFitnessDiagnosticsRequestViewController : OBTextWelcomeController {
    id /* block */  _completionHandler;
}

@property (nonatomic, copy) id /* block */ completionHandler;

+ (bool)needsRequestedPermission;
+ (void)presentInViewController:(id)arg1;
+ (void)presentInViewController:(id)arg1 withCompletionHandler:(id /* block */)arg2;

- (void).cxx_destruct;
- (void)_disableDataCollection;
- (void)_enableDataCollection;
- (void)_showDataCollectionAdditionalInfo;
- (id /* block */)completionHandler;
- (void)dismissFitnessController;
- (void)setCompletionHandler:(id /* block */)arg1;
- (bool)shouldInlineButtonTray;
- (void)viewDidLoad;

@end
