/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKMedicalIDEditorLanguageCell : HKMedicalIDEditorCell {
    id /* block */  _editAction;
    NSString * _valueText;
}

@property (nonatomic, copy) id /* block */ editAction;
@property (nonatomic, retain) NSString *valueText;

- (void).cxx_destruct;
- (void)beginEditing;
- (id /* block */)editAction;
- (void)setBeginEditAction:(id /* block */)arg1;
- (void)setEditAction:(id /* block */)arg1;
- (void)setValueLanguageText:(id)arg1;
- (void)setValueText:(id)arg1;
- (id)valueText;

@end
