/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKMedicalIDEmergencyAccessLearnMoreCell : UITableViewCell {
    NSAttributedString * _body;
    UITextView * _bodyTextView;
    NSString * _title;
    UILabel * _titleLabel;
}

@property (nonatomic, copy) NSAttributedString *body;
@property (nonatomic, copy) NSString *title;

- (void).cxx_destruct;
- (void)_addSubviews;
- (void)_setUpConstraints;
- (void)_setUpViews;
- (id)body;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setBody:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)title;

@end
