/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewDeviceOutreachUI.framework/NewDeviceOutreachUI
 */

@interface NDOSpecifierDataSource : PSSpecifierDataSource <NDOAppleCareFlowDelegate> {
    bool  _hasLoadedSpecifiers;
    NDOManager * _ndoManager;
    NSArray * _ndoSpecifiers;
}

@property (nonatomic, retain) NDOManager *ndoManager;
@property (nonatomic, retain) NSArray *ndoSpecifiers;

- (void).cxx_destruct;
- (id)acController;
- (bool)areSpecifiersLoaded;
- (id)init;
- (void)loadSpecifiers;
- (void)ndoAppleCareCoveragePressed:(id)arg1;
- (id)ndoManager;
- (id)ndoSpecifiers;
- (void)outreachFinishedWithCompletion:(unsigned long long)arg1;
- (void)reloadSpecifiers;
- (void)setNdoManager:(id)arg1;
- (void)setNdoSpecifiers:(id)arg1;
- (void)updateNDOSpecifiersWithPolicy:(unsigned long long)arg1 completion:(id /* block */)arg2;
- (id)warrantyDetailText:(id)arg1;
- (id)warrantySpecifiersFromWarranty:(id)arg1;

@end
