/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/KnowledgeGraphKit.framework/KnowledgeGraphKit
 */

@interface KnowledgeGraphKit.MANaiveBayesClassifier : _TtCs12_SwiftObject {
    void classes;
    void data;
    void training;
}

@end
