/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.DragViewResponder : SwiftUI.DefaultLayoutViewResponder {
    void itemsForDragHandler;
    void targetRect;
}

@end
