/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.ReportConcernCommandHandler : _TtCs12_SwiftObject {
    void reportConcernModule;
}

@end
