/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.PDFReplicaViewerRenderer : _TtCs12_SwiftObject {
    void styler;
}

@end
