/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.TodayDataManager : _TtCs12_SwiftObject {
    void accessQueue;
    void feedService;
    void feedServiceConfigFetcher;
    void paidBundleConfiguration;
}

@end
