/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.RecordIDURLHandler : _TtCs12_SwiftObject {
    void magazineActivityNavigator;
    void patterns;
}

@end
