/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.SpecialEventsHeadlineModel : _TtCs12_SwiftObject {
    void action;
    void headlineModel;
    void style;
    void title;
}

@end
