/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.TopVideosBlueprintViewCellProvider : _TtCs12_SwiftObject {
    void delegate;
    void videoOnTopRenderer;
}

@end
