/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.SearchMoreArticleService : _TtCs12_SwiftObject {
    void articleStreamingResults;
    void headlineModelFactory;
    void noMoreSearchResults;
}

@end
