/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.HeadlineViewImageOnSideLayoutAttributesFactory : _TtCs12_SwiftObject {
    void footerViewlayoutAttributesFactory;
    void offensiveViewLayoutAttributesFactory;
    void textViewLayoutAttributesFactory;
}

@end
