/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.HeadlineViewWrappedImageOnSideStyleFactory : _TtCs12_SwiftObject {
    void footerViewStyleFactory;
    void textViewStyleFactory;
}

@end
