/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.HeadlineViewImageOnSidePropertiesFactory : _TtCs12_SwiftObject {
    void footerViewPropertiesFactory;
    void textViewPropertiesFactory;
}

@end
