/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.NotificationResponseHandlerManager : _TtCs12_SwiftObject {
    void handlers;
}

@end
