/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.PaywallCoordinator : _TtCs12_SwiftObject {
    void adReferralData;
    void articleData;
    void campaignData;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  paywallModel;
    void tracker;
}

@end
