/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ForYouTitleViewLayoutAttributesFactory : _TtCs12_SwiftObject {
    void cache;
}

@end
