/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.MagazineFeedGroupTitleViewRenderer : _TtCs12_SwiftObject {
    void blueprintProvider;
    void debugEnabled;
    void dislikeButtonRenderer;
    void feedPersonalizer;
    void likeButtonRenderer;
    void paidAccessChecker;
    void privateDataDirectory;
    void shineImageFactory;
    void styler;
    void tagController;
}

@end
