/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.HeadlineViewImageOnSideRenderer : _TtCs12_SwiftObject {
    void footerViewRenderer;
    void offensiveViewRenderer;
    void textViewRenderer;
    void thumbnailImageCache;
}

@end
