/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.StubFeaturedIssueArticleMagazineFeedGroupEmitter : _TtCs12_SwiftObject {
    void config;
}

@end
