/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.MoreVideosDataManager : _TtCs12_SwiftObject {
    void delegate;
    void historyService;
    void savedService;
}

@end
