/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.FollowingNotificationsLayoutBuilder : _TtCs12_SwiftObject {
    void followingRowViewLayoutAttributesFactory;
    void titleViewLayoutAttributesFactory;
}

@end
