/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NUPaywallEventData : NSObject {
    void articleData;
    void channel;
    void feedData;
    void groupData;
    void qToken;
    void referral;
    void viewData;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithPaywallViewData:(id)arg1 headline:(id)arg2 channel:(id)arg3 feed:(id)arg4 paywallGroupData:(id)arg5 referral:(id)arg6 qToken:(id)arg7;

@end
