/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface TSJournalDataSource : NSObject {
    void configModels;
    void feedPersonalizer;
    void groupTitle;
    void headlineModels;
    void paidAccessChecker;
    void privateDataDirectory;
    void tagController;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithFeedPersonalizer:(id)arg1 tagController:(id)arg2 privateDataDirectory:(id)arg3 group:(id)arg4 paidAccessChecker:(id)arg5;

@end
