/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface _TtCC8VideosUI18DecoratedShelfView11ContentView : UIView {
    void $__lazy_storage_$_logoGradientView;
    void $__lazy_storage_$_twoLineShelfLockupComputationLabel;
    void backgroundMediaController;
    void backgroundViewModel;
    void channelLogoView;
    void debugUIEnabled;
    void didHostMediaController;
    void gradientLayer;
    void hostMediaController;
    void logoImageView;
    void opacityMaskLayer;
    void platterView;
    void shelfMode;
    void shelfRowMetrics;
    void shelfView;
    void verticalStackView;
    void viewModel;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;
- (void)traitCollectionDidChange:(id)arg1;

@end
