/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface _TtCO8VideosUI15ImageDescriptorP33_5F44B378E4B755AED772E9F34358B5225Image : _TtCs12_SwiftObject {
    void crop;
    void darkSrc;
    void format;
    void isResource;
    void isTemplated;
    void layoutDictionary;
    void placeHolderSrc;
    void src;
    void themeString;
}

@end
