/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.DecoratedShelfLayout : VideosUI.ViewLayout {
    void $__lazy_storage_$_alphaImageLayout;
    void $__lazy_storage_$_channelLogoLayout;
    void $__lazy_storage_$_logoImageLayout;
    void $__lazy_storage_$_shelfLayout;
    void $__lazy_storage_$_verticalStackLayout;
}

- (id)copyWithZone:(void*)arg1;

@end
