/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.ScrollViewMonitor : _TtCs12_SwiftObject {
    void contentOffsetSubscriber;
    void scrollView;
}

@end
