/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.ErrorTemplateLayout : VideosUI.ViewLayout {
    void debugTextLayout;
    void debugTextLayout2;
    void descriptionTextlayout;
    void titleTextLayout;
}

@end
