/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.TextViewModel : VideosUI.ViewModel {
    void computedAttributedString;
    void imgageLayout;
    void value;
}

@end
