/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.Document : _TtCs12_SwiftObject {
    void appContext;
    void navigationBar;
    void template;
}

@end
