/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.ButtonLayout : VideosUI.ViewLayout {
    void $__lazy_storage_$_buttonTitleStyle;
    void $__lazy_storage_$_buttonType;
    void $__lazy_storage_$_vuiButtonLayout;
}

@end
