/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.PageSwipeUpViewLayout : VideosUI.ViewLayout {
    void baselineMarginToChevron;
    void chevronImageLayout;
    void heightOfGradientView;
    void textLayout;
    void topMarginOfChevron;
}

@end
