/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.ImageLayout : VideosUI.ViewLayout {
    void aspectRatio;
    void borderColor;
    void borderWidth;
    void continuousBorder;
    void scaleMode;
    void upscaleFactor;
}

@end
