/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.ChannelLogoViewLayout : VideosUI.ViewLayout {
    void appleTVChannelImageViewLayout;
    void logoImageViewLayout;
}

@end
