/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.TextLayout : VideosUI.ViewLayout {
    void alwaysFocusable;
    void fontFamily;
    void fontFeature;
    void fontSize;
    void fontWeight;
    void letterSpacing;
    void maximumContentSizeCategory;
    void minimumScaleFactor;
    void numberOfLines;
    void numberOfLinesAXLarge;
    void numberOfLinesAXSmall;
    void textAlignment;
    void textStyle;
    void textTransform;
}

@end
