/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.ImageViewModel : VideosUI.ViewModel {
    void accessibilityText;
    void alternateImages;
    void defaultImage;
}

@end
