/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideosUI.framework/VideosUI
 */

@interface VideosUI.DocumentParser : _TtCs12_SwiftObject {
    void document;
    void jsonData;
}

@end
