/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CheckerBoardServices.framework/CheckerBoardServices
 */

@interface CBSUtilities : NSObject

+ (void)dimDisplay;
+ (void)disableNetworkReconnect;
+ (void)enableNetworkReconnect;
+ (void)exitCheckerBoard;
+ (void)hideSceneStatusBar;
+ (bool)isCheckerBoardActive;
+ (id)proxyServer;
+ (void)sceneStatusBarStyle:(long long)arg1;
+ (void)showSceneStatusBar;
+ (void)undimDisplay;

@end
