/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCLocalRegion : NSObject {
    NSArray * _autoFavoriteTagIDs;
    NSString * _identifier;
    NSArray * _localVersionedTagIDs;
    NSString * _name;
}

@property (nonatomic, retain) NSArray *autoFavoriteTagIDs;
@property (nonatomic, retain) NSString *identifier;
@property (nonatomic, retain) NSArray *localVersionedTagIDs;
@property (nonatomic, retain) NSString *name;

- (void).cxx_destruct;
- (id)autoFavoriteTagIDs;
- (id)description;
- (id)identifier;
- (id)init;
- (id)initWithDictionary:(id)arg1;
- (id)localVersionedTagIDs;
- (id)name;
- (void)setAutoFavoriteTagIDs:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setLocalVersionedTagIDs:(id)arg1;
- (void)setName:(id)arg1;

@end
