/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperienceUI.framework/HealthExperienceUI
 */

@interface HealthExperienceUI.CategoryViewDataSourceProvider : _TtCs12_SwiftObject {
    void categoryPredicate;
    void chrOnly;
    void store;
}

@end
