/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperienceUI.framework/HealthExperienceUI
 */

@interface HealthExperienceUI.RestorationDefaultStoreProvider : _TtCs12_SwiftObject {
    void didDecode;
    void resolvedExperienceStore;
    void resolvedHealthStore;
    void resolvedHealthToolbox;
}

@end
