/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperienceUI.framework/HealthExperienceUI
 */

@interface HealthExperienceUI.PluginRestorationHandler : _TtCs12_SwiftObject {
    void presentingViewController;
}

@end
