/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreRepairKit.framework/CoreRepairKit
 */

@interface CRRepairStatus : NSObject

+ (id)_getDataForDataClass:(id)arg1;
+ (id)_getStringFromCert:(struct { char *x1; char *x2; })arg1 WithTag:(unsigned long long)arg2 AndOID:(id)arg3;
+ (id)_hasHadBatteryRepairForDataClass:(id)arg1;
+ (bool)hasHadAuthorizedRepairForComponent:(unsigned long long)arg1;

@end
