/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Coherence.framework/Coherence
 */

@interface Coherence.CopiedReference : _TtCs12_SwiftObject {
    void copied;
    void reference;
}

@end
