/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface _TtCE16HealthExperienceCSo14HKCategoryType31MenstrualSymptomAppetiteChanges : _TtCs12_SwiftObject

@end
