/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface HealthExperience.CancellableProgressList : _TtCs12_SwiftObject {
    void list;
    void lock;
}

@end
