/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface HealthExperience.HKHealthSource : _TtCs12_SwiftObject {
    void bundleIdentifier;
    void name;
}

@end
