/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface HealthExperience.HealthExperienceStoreModel : _TtCs12_SwiftObject

@end
