/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface HealthExperience.DisplayType : _TtCs12_SwiftObject {
    void identifier;
    void isHidden;
}

@end
