/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface HealthExperience.ModelTrainingScenarioExecutor : _TtCs12_SwiftObject {
    void coordinator;
    void store;
}

@end
