/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface HealthExperience.BasicPluginInfo : _TtCs12_SwiftObject {
    void bundle;
    void bundleIdentifier;
}

@end
