/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface HealthExperience.UnfairLock : _TtCs12_SwiftObject {
    void underlyingLock;
}

@end
