/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthExperience.framework/HealthExperience
 */

@interface HealthExperience.Matcher : _TtCs12_SwiftObject {
    void constraintPredicates;
}

@end
