/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriKitFlow.framework/SiriKitFlow
 */

@interface SiriKitFlow.OfferToContinueFlowFrame : SiriKitFlow.ConfirmationFlowFrame

@end
