/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DistributedEvaluation.framework/DistributedEvaluation
 */

@interface DistributedEvaluation.SecureAggregationAPIAsyncClient : _TtCs12_SwiftObject {
    void invocable;
}

@end
