/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Notes.framework/Notes
 */

@interface ICMutableSetSecureUnarchiveFromDataTransformer : NSSecureUnarchiveFromDataTransformer

+ (id)allowedTopLevelClasses;

@end
