/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface PSSystemPolicyForApp : NSObject {
    NSString * _bundleIdentifier;
    <PSSystemPolicyForAppDelegate> * _delegate;
    bool  _forcePolicyOptions;
    PSPhotosPolicyController * _photosPrivacyController;
    unsigned long long  _policyOptions;
    NSString * _selectedAppBundleID;
}

@property (nonatomic, copy) NSString *bundleIdentifier;
@property (nonatomic) <PSSystemPolicyForAppDelegate> *delegate;
@property (nonatomic, retain) NSString *selectedAppBundleID;

+ (bool)isServiceRestricted:(id)arg1;

- (void).cxx_destruct;
- (bool)_isBackgroundAppRefreshAllowed;
- (bool)_isLocationServicesRestricted;
- (bool)_isWirelessDataRestricted;
- (id)_privacyAccessForService:(struct __CFString { }*)arg1;
- (bool)_supportsBackgroundAppRefresh;
- (id)assistantAndSearchSpecifiers;
- (id)authLevelStringForStatus:(unsigned long long)arg1;
- (id)backgroundAppRefreshSpecifier;
- (id)bundleIdentifier;
- (struct __CFBundle { }*)copyTCCBundleForService:(struct __CFString { }*)arg1;
- (id)dataUsageWorkspaceInfo;
- (id)delegate;
- (id)documentSource:(id)arg1;
- (id)documentsSpecifier;
- (void)exposureLoggingSettingsWasTapped;
- (id)exposureSpecifiers;
- (id)initWithBundleIdentifier:(id)arg1;
- (id)isBackgroundRefreshEnabled:(id)arg1;
- (bool)isCellularBundleID:(id)arg1;
- (id)locationServicesSpecifier;
- (id)locationStatus:(id)arg1;
- (id)notificationSpecifier;
- (id)photosServicesSpecifier;
- (id)preferredLanguage:(id)arg1;
- (id)preferredLanguageSpecifier;
- (id)privacyAccessForSpecifier:(id)arg1;
- (id)privacySpecifierForService:(struct __CFString { }*)arg1;
- (id)privacySpecifiers;
- (id)selectedAppBundleID;
- (void)setBackgroundRefreshEnabled:(id)arg1 forSpecifier:(id)arg2;
- (void)setBundleIdentifier:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setPrivacyAccess:(id)arg1 forSpecifier:(id)arg2;
- (void)setSelectedAppBundleID:(id)arg1;
- (id)specifiers;
- (id)specifiersForPolicyOptions:(unsigned long long)arg1 force:(bool)arg2;
- (id)wirelessDataSpecifierWithAppName:(id)arg1;

@end
