/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIClickPresentationFeedbackGenerator : UIFeedbackGenerator <UIFeedbackGeneratorUserInteractionDriven>

// Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

+ (Class)_configurationClass;

- (id)_clickConfiguration;
- (void)dragged;
- (id)initWithCoordinateSpace:(id)arg1;
- (void)userInteractionCancelled;
- (void)userInteractionEnded;
- (void)userInteractionStarted;

// Image: /Library/MobileSubstrate/DynamicLibraries/Orion.dylib

- (void)popped;
- (void)previewed;

@end
