/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UICustomDiscreteFeedback : _UIDiscreteFeedback {
    unsigned long long  _eventType;
    unsigned int  _systemSoundID;
}

@property (nonatomic, readonly) unsigned long long eventType;
@property (nonatomic, readonly) unsigned int systemSoundID;

// Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

+ (id)type;

- (unsigned long long)_effectiveEventType;
- (unsigned int)_effectiveSystemSoundID;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)dictionaryRepresentation;
- (unsigned long long)eventType;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (bool)isEqual:(id)arg1;
- (unsigned int)systemSoundID;

// Image: /Library/MobileSubstrate/DynamicLibraries/Orion.dylib

+ (id)customDiscreteFeedbackWithEventType:(unsigned long long)arg1 systemSoundID:(unsigned int)arg2;

@end
