/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIInterfaceActionGroupHeaderScrollView : _UIAlertControllerShadowedScrollView {
    NSArray * _constraints;
    UIView * _contentView;
}

@property (nonatomic, readonly) UIView *contentView;

// Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

- (void).cxx_destruct;
- (double)_contentFitCanScrollThreshold;
- (void)accessoryInsetsDidChange:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (id)contentView;
- (id)initWithContentView:(id)arg1;

// Image: /Library/MobileSubstrate/DynamicLibraries/snell.dylib

- (void)updateConstraints;

@end
