/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatusBarSignalView : _UIStatusBarPersistentAnimationView <_UIStatusBarDisplayable> {
    UIColor * _activeColor;
    long long  _iconSize;
    UIColor * _inactiveColor;
    long long  _numberOfActiveBars;
    long long  _numberOfBars;
    long long  _signalMode;
    bool  _smallSize;
}

@property (nonatomic, readonly) UIAccessibilityHUDItem *accessibilityHUDRepresentation;
@property (nonatomic, copy) UIColor *activeColor;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long iconSize;
@property (nonatomic, copy) UIColor *inactiveColor;
@property (nonatomic) long long numberOfActiveBars;
@property (nonatomic) long long numberOfBars;
@property (nonatomic, readonly) long long overriddenVerticalAlignment;
@property (nonatomic, readonly) bool prefersBaselineAlignment;
@property (nonatomic) long long signalMode;
@property (nonatomic) bool smallSize;
@property (readonly) Class superclass;
@property (nonatomic, readonly) bool wantsCrossfade;

// Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

+ (struct CGSize { double x1; double x2; })_intrinsicContentSizeForNumberOfBars:(long long)arg1 iconSize:(long long)arg2;

- (void).cxx_destruct;
- (void)_colorsDidChange;
- (void)_iconSizeDidChange;
- (void)_updateFromMode:(long long)arg1;
- (id)activeColor;
- (void)applyStyleAttributes:(id)arg1;
- (long long)iconSize;
- (id)inactiveColor;
- (long long)numberOfActiveBars;
- (long long)numberOfBars;
- (void)setIconSize:(long long)arg1;
- (void)setNumberOfBars:(long long)arg1;
- (void)setSmallSize:(bool)arg1;
- (long long)signalMode;
- (bool)smallSize;

// Image: /Library/MobileSubstrate/DynamicLibraries/SnowBoardStatusBarSB.dylib

- (void)_updateActiveBars;
- (void)_updateBars;
- (struct CGImage { }*)currentImage;
- (id)real_activeColor;
- (id)real_inActiveColor;
- (id)sbImageLayer;
- (void)setActiveColor:(id)arg1;
- (void)setFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setInactiveColor:(id)arg1;
- (void)setNumberOfActiveBars:(long long)arg1;
- (void)setReal_activeColor:(id)arg1;
- (void)setReal_inActiveColor:(id)arg1;
- (void)setSbImageLayer:(id)arg1;
- (void)setSignalMode:(long long)arg1;
- (void)setupImageViewWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)updateImage;

@end
