/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatusBarImageProvider : NSObject

// Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore

+ (id)sharedProvider;

- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_alignmentInsetsForImageNamed:(id)arg1 styleAttributes:(id)arg2;
- (bool)_suppressHairlineThickeningForImageName:(id)arg1 styleAttributes:(id)arg2;

// Image: /Library/MobileSubstrate/DynamicLibraries/SnowBoardStatusBarSB.dylib

- (id)imageNamed:(id)arg1 styleAttributes:(id)arg2;

@end
