/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.JSGarbageCollector : _TtCs12_SwiftObject {
    void lastShrinkTime;
    void shrinkTimeGuard;
    void stack;
}

@end
