/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.EditorialQuote : _TtCs12_SwiftObject {
    void attribution;
    void impressionMetrics;
    void text;
}

@end
