/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.CompoundMetricsRecorder : _TtCs12_SwiftObject {
    void queue;
    void recorders;
}

@end
