/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.ArcadeAccountEventGenerator : _TtCs12_SwiftObject {
    void metricsPipeline;
}

@end
