/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.InMemoryMetricsRecorder : _TtCs12_SwiftObject {
    void delegate;
    void events;
    void historySize;
    void stateLock;
}

@end
