/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.SmallBreakout : _TtCs12_SwiftObject {
    void backgroundColor;
    void clickAction;
    void details;
    void iconArtwork;
    void impressionMetrics;
    void offerDisplayProperties;
}

@end
