/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.Link : _TtCs12_SwiftObject {
    void clickAction;
    void descriptionText;
    void impressionMetrics;
    void linkPresentationEnabled;
    void summaryText;
}

@end
