/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.ArcadeFooter : _TtCs12_SwiftObject {
    void backgroundColor;
    void buttonAction;
    void footnote;
    void icons;
    void impressionMetrics;
}

@end
