/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.FastImpressionsCatalogue : _TtCs12_SwiftObject {
    void delegate;
    void fastCatalogue;
    void impressionableThreshold;
    void mainCatalogue;
}

@end
