/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.ArcadeWelcomePage : _TtCs12_SwiftObject {
    void createNewFamilyContent;
    void familyOrganizerContent;
    void pageMetrics;
}

@end
