/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.FigaroMetricsRecorder : _TtCs12_SwiftObject {
    void defaultTopic;
    void metrics;
}

@end
