/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.ClientControlButton : _TtCs12_SwiftObject {
    void buttonAction;
    void impressionMetrics;
    void title;
}

@end
