/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.SearchHintSet : _TtCs12_SwiftObject {
    void hints;
    void pageMetrics;
}

@end
