/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.TodayCardMedia : _TtCs12_SwiftObject {
    void impressionMetrics;
    void kind;
    void titleBackingGradient;
}

@end
