/* Generated by RuntimeBrowser.
 */

@protocol AMSUIWebPagePresenter <NSObject>

@required

- (void)applyPageModel:(AMSUIWebModel<AMSUIWebPageProvider> *)arg1;
- (AMSUIWebModel<AMSUIWebPageProvider> *)model;

@end
