/* Generated by RuntimeBrowser.
 */

@protocol CRKASMUser <NSObject>

@required

- (NSString *)appleID;
- (NSString *)identifier;
- (<CRKASMNameComponents> *)nameComponents;
- (<CRKASMOrganization> *)organization;

@end
