/* Generated by RuntimeBrowser.
 */

@protocol CSSystemCursorInteractionManaging <NSObject>

@required

- (void)registerView:(UIView *)arg1 delegate:(id <SBSystemCursorInteractionDelegate>)arg2;
- (void)unregisterView:(UIView *)arg1;

@end
