/* Generated by RuntimeBrowser.
 */

@protocol NPKCommutePlanField <NPKTransitItemField>

@required

- (NSString *)detailLabel;
- (bool)isCountBasedCommutePlan;
- (<NPKDateRange> *)usageDateRange;

@end
