/* Generated by RuntimeBrowser.
 */

@protocol NPKTransitItemField <NSObject>

@required

- (PKPaymentPassAction *)action;
- (NSString *)detailLabel;
- (NSString *)formattedValue;
- (bool)hasPendingUpdate;
- (NSString *)identifier;
- (NSString *)label;

@end
