/* Generated by RuntimeBrowser.
 */

@protocol PMLMultiLabelClassifierModelProtocol <NSObject>

@required

- (NSArray *)classify:(PMLSparseVector *)arg1;
- (unsigned long long)count;
- (NSArray *)predict:(PMLSparseVector *)arg1;

@end
