/* Generated by RuntimeBrowser.
 */

@protocol SHMatcher <NSObject>

@required

- (<SHMatcherDelegate> *)delegate;
- (void)match:(SHSignature *)arg1;
- (void)setDelegate:(id <SHMatcherDelegate>)arg1;

@end
