/* Generated by RuntimeBrowser.
 */

@protocol SnowBoardExtension <NSObject>

@optional

+ (int)priority;

- (void)clearThemes;
- (void)dispose;
- (NSArray *)extraSearchPaths;
- (void)loadPath:(NSString *)arg1;
- (UIImage *)processIcon:(UIImage *)arg1;
- (bool)requiresRespring;
- (bool)requiresUICache;
- (NSString *)settingsViewControllerClass;
- (UIImage *)tabBarIcon;
- (struct CGSize { double x1; double x2; })tabBarIconSize;
- (NSString *)tabBarTitle;
- (bool)wouldProcessIcon;

@end
