/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKExpressAuthorizationPaymentRequestContext : NSObject {
    id /* block */  _completionHandler;
    LAContext * _context;
    PKPaymentPass * _pass;
    NSSet * _result;
}

@property (nonatomic, copy) id /* block */ completionHandler;
@property (nonatomic) LAContext *context;
@property (nonatomic, retain) PKPaymentPass *pass;
@property (nonatomic, retain) NSSet *result;

- (void).cxx_destruct;
- (id /* block */)completionHandler;
- (id)context;
- (void)dealloc;
- (void)invokeCompletion;
- (id)pass;
- (id)result;
- (void)setCompletionHandler:(id /* block */)arg1;
- (void)setContext:(id)arg1;
- (void)setPass:(id)arg1;
- (void)setResult:(id)arg1;

@end
