/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServicesUIDynamic.framework/AppleMediaServicesUIDynamic
 */

@interface AppleMediaServicesUIDynamic.ServiceRequestHandler : _TtCs12_SwiftObject {
    void accessQueue;
    void isConfigured;
    void javaScriptUrlPromise;
    void objectGraph;
}

@end
