/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServicesUIDynamic.framework/AppleMediaServicesUIDynamic
 */

@interface AppleMediaServicesUIDynamic.PagePluginLoader : _TtCs12_SwiftObject {
    void pageDefinitionCache;
    void pluginLoader;
}

@end
