/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServicesUIDynamic.framework/AppleMediaServicesUIDynamic
 */

@interface AppleMediaServicesUIDynamic.AMSUIDMetricsEventRecorder : _TtCs12_SwiftObject {
    void metricsEventRecorder;
}

@end
