/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServicesUIDynamic.framework/AppleMediaServicesUIDynamic
 */

@interface AppleMediaServicesUIDynamic.ActionMapperFactory : _TtCs12_SwiftObject {
    void actionTypes;
}

@end
