/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServicesUIDynamic.framework/AppleMediaServicesUIDynamic
 */

@interface AppleMediaServicesUIDynamic.AMSUIDMetricsPipelineProvider : _TtCs12_SwiftObject {
    void objectGraph;
}

@end
