/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoPassKit.framework/NanoPassKit
 */

@interface NPKAudioPlayer : NSObject

+ (void)_playSoundsWithIdentifier:(unsigned int)arg1;
+ (void)playAccessScanCompleteHaptic;
+ (void)playProvisioningFailureHaptic;
+ (void)playProvisioningSuccessHaptic;
+ (void)playTransactionFailureHaptic;
+ (void)playTransactionSuccessHaptic;
+ (void)playWarsawHaptic;

@end
