/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoPassKit.framework/NanoPassKit
 */

@interface NPKSubcredentialSetExpressCoordinator : NSObject <PKPaymentAuthorizationControllerDelegate, PKPaymentAuthorizationControllerPrivateDelegate> {
    id /* block */  _completion;
    LAContext * _context;
}

@property (nonatomic, copy) id /* block */ completion;
@property (nonatomic, retain) LAContext *context;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_errorWithCode:(long long)arg1 message:(id)arg2;
- (void)_invokeCompletionWithContext:(id)arg1 error:(id)arg2;
- (id /* block */)completion;
- (id)context;
- (void)paymentAuthorizationController:(id)arg1 didAuthorizeContextWithHandler:(id /* block */)arg2;
- (void)paymentAuthorizationControllerDidFinish:(id)arg1;
- (void)requestExpressAuthorizationForCredentialedPass:(id)arg1 context:(id)arg2 withCompletion:(id /* block */)arg3;
- (void)setCompletion:(id /* block */)arg1;
- (void)setContext:(id)arg1;

@end
