/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKASMConcreteOrganization : NSObject <CRKASMOrganization> {
    NSUUID * _UUID;
}

@property (nonatomic, retain) NSUUID *UUID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)UUID;
- (id)description;
- (unsigned long long)hash;
- (id)initWithPerson:(id)arg1;
- (bool)isEqual:(id)arg1;
- (void)setUUID:(id)arg1;

@end
