/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKASMConcreteUserDirectory : NSObject <CRKASMUserDirectory> {
    <CRKClassKitRosterRequirements> * _requirements;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) <CRKClassKitRosterRequirements> *requirements;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)initWithRequirements:(id)arg1;
- (id)iteratorForSearchString:(id)arg1 sortingGivenNameFirst:(bool)arg2 pageSize:(long long)arg3;
- (id)requirements;

@end
