/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKASMCourseUpdateProperties : NSObject <NSCopying> {
    NSNumber * _color;
    NSNumber * _mascot;
    NSString * _name;
    NSSet * _usersToAdd;
    NSSet * _usersToRemove;
}

@property (nonatomic, retain) NSNumber *color;
@property (nonatomic, retain) NSNumber *mascot;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSSet *usersToAdd;
@property (nonatomic, copy) NSSet *usersToRemove;

- (void).cxx_destruct;
- (id)color;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)mascot;
- (id)name;
- (void)setColor:(id)arg1;
- (void)setMascot:(id)arg1;
- (void)setName:(id)arg1;
- (void)setUsersToAdd:(id)arg1;
- (void)setUsersToRemove:(id)arg1;
- (id)usersToAdd;
- (id)usersToRemove;

@end
