/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKASMConcreteCourse : NSObject <CRKASMCourse> {
    NSString * _backingClassObjectID;
    CRKASMCertificateVendor * _certificateVendor;
    unsigned long long  _color;
    bool  _editable;
    DMFControlGroupIdentifier * _identifier;
    CRKASMIdentityVendor * _identityVendor;
    <CRKASMLocation> * _location;
    unsigned long long  _mascot;
    NSString * _name;
    NSSet * _trustedUserIdentifiers;
    NSArray * _trustedUsers;
}

@property (nonatomic, readonly, copy) NSSet *allTrustedUserCertificates;
@property (nonatomic, readonly, copy) NSString *backingClassObjectID;
@property (nonatomic, readonly) CRKASMCertificateVendor *certificateVendor;
@property (nonatomic, readonly) unsigned long long color;
@property (getter=isEditable, nonatomic, readonly) bool editable;
@property (nonatomic, readonly, copy) DMFControlGroupIdentifier *identifier;
@property (nonatomic, readonly) <CRKIdentity> *identity;
@property (nonatomic, readonly) CRKASMIdentityVendor *identityVendor;
@property (nonatomic, readonly) <CRKASMLocation> *location;
@property (nonatomic, readonly) unsigned long long mascot;
@property (nonatomic, readonly, copy) NSString *name;
@property (nonatomic, readonly, copy) NSSet *trustedUserIdentifiers;
@property (nonatomic, readonly, copy) NSArray *trustedUsers;

+ (id)courseNameforClass:(id)arg1;
+ (id)trustedUserIdentifierForTrustedUsers:(id)arg1;
+ (id)trustedUsersFromPersons:(id)arg1 certificateVendor:(id)arg2;

- (void).cxx_destruct;
- (id)allTrustedUserCertificates;
- (id)backingClassObjectID;
- (id)certificateVendor;
- (unsigned long long)color;
- (id)description;
- (unsigned long long)hash;
- (id)identifier;
- (id)identity;
- (id)identityVendor;
- (id)initWithBackingClass:(id)arg1 location:(id)arg2 persons:(id)arg3 identityVendor:(id)arg4 certificateVendor:(id)arg5 manageableLocationIDs:(id)arg6;
- (bool)isEditable;
- (bool)isEqual:(id)arg1;
- (id)location;
- (unsigned long long)mascot;
- (id)name;
- (id)trustedUserIdentifiers;
- (id)trustedUsers;

@end
