/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKClassKitAccountEligibilityProvider : NSObject {
    ACAccountStore * _accountStore;
    bool  _eligibleAccountSignedIn;
}

@property (nonatomic, readonly) ACAccountStore *accountStore;
@property (getter=isEligibleAccountSignedIn, nonatomic) bool eligibleAccountSignedIn;

- (void).cxx_destruct;
- (id)accountStore;
- (void)accountStoreDidChange:(id)arg1;
- (void)dealloc;
- (id)init;
- (bool)isEligibleAccountSignedIn;
- (void)setEligibleAccountSignedIn:(bool)arg1;
- (void)update;

@end
