/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKConcreteClassKitRosterRequirements : NSObject <CRKClassKitRosterRequirements> {
    NSObject<CRKClassKitFacade> * _classKitFacade;
    NSArray * _dataObservers;
    bool  _forInstructor;
    int  _membershipChangeDarwinNotificationToken;
    NSMutableDictionary * _observersByToken;
}

@property (nonatomic, readonly) NSObject<CRKClassKitFacade> *classKitFacade;
@property (nonatomic, readonly, copy) NSArray *dataObservers;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (getter=isEligibleAccountSignedIn, nonatomic, readonly) bool eligibleAccountSignedIn;
@property (getter=isForInstructor, nonatomic, readonly) bool forInstructor;
@property (readonly) unsigned long long hash;
@property (nonatomic) int membershipChangeDarwinNotificationToken;
@property (nonatomic, readonly) NSMutableDictionary *observersByToken;
@property (readonly) Class superclass;

+ (id)instructorRosterRequirementsWithClassKitFacade:(id)arg1;
+ (id)studentRosterRequirementsWithClassKitFacade:(id)arg1;

- (void).cxx_destruct;
- (void)addNullableObserver:(id)arg1 toArray:(id)arg2;
- (id)addObserver:(id /* block */)arg1;
- (void)addPerson:(id)arg1 toClass:(id)arg2;
- (void)addTrustedPerson:(id)arg1 toClass:(id)arg2;
- (void)callObserversWithReason:(id)arg1;
- (id)classKitFacade;
- (void)classesWithCompletion:(id /* block */)arg1;
- (void)currentUserDidChange:(id)arg1;
- (void)currentUserWithCompletion:(id /* block */)arg1;
- (id)dataObservers;
- (void)dealloc;
- (void)deregisterDataObservers;
- (void)executeQuery:(id)arg1;
- (id)initWithClassKitFacade:(id)arg1 isForInstructor:(bool)arg2;
- (bool)isEligibleAccountSignedIn;
- (bool)isForInstructor;
- (bool)isForStudent;
- (void)locationsWithManagePermissionsForUserWithObjectID:(id)arg1 completion:(id /* block */)arg2;
- (void)locationsWithObjectIDs:(id)arg1 completion:(id /* block */)arg2;
- (id)makeClassWithLocationID:(id)arg1 name:(id)arg2;
- (id /* block */)makeDataChangedBlockWithObserverDescription:(id)arg1;
- (id)makeDataObservers;
- (id)makePersonQueryForSearchString:(id)arg1 sortingGivenNameFirst:(bool)arg2 pageSize:(long long)arg3;
- (int)membershipChangeDarwinNotificationToken;
- (id)objectIDsOfTrustedPersonsInClass:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (id)observersByToken;
- (void)registerDataObservers;
- (void)registerForCurrentUserChangeNotification;
- (void)registerForMembershipChangeDarwinNotification;
- (void)removeClass:(id)arg1 completion:(id /* block */)arg2;
- (void)removeObserver:(id)arg1;
- (void)removeTrustedPerson:(id)arg1 fromClass:(id)arg2;
- (void)saveClass:(id)arg1 completion:(id /* block */)arg2;
- (void)setMembershipChangeDarwinNotificationToken:(int)arg1;
- (void)startObservingAccountEligibility;
- (void)stopObservingAccountEligibility;
- (void)trustedPersonsInClassWithObjectID:(id)arg1 completion:(id /* block */)arg2;
- (void)unregisterForMembershipChangeDarwinNotification;

@end
