/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI
 */

@interface TeaUI.ButtonWindowToolbar2ItemHandler : _TtCs12_SwiftObject {
    void canHandleClosure;
    void handleClosure;
}

@end
