/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI
 */

@interface TeaUI.CommandCenter : _TtCs12_SwiftObject {
    void contextStore;
    void handlers;
    void observers;
}

@end
