/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI
 */

@interface TeaUI.MastheadViewScaleAnimator : _TtCs12_SwiftObject {
    void animation;
    void animationVelocityThreshold;
    void viewProvider;
}

@end
