/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMObjectCacheNSString : NSObject

+ (id)cachedInstanceForString:(id)arg1;

@end
