/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriAudioSupport.framework/SiriAudioSupport
 */

@interface _TtCV16SiriAudioSupport19SiriRemembersSignal18AppMatchesProvider : _TtCs12_SwiftObject

@end
