/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriAudioSupport.framework/SiriAudioSupport
 */

@interface _TtCV16SiriAudioSupport20LastNowPlayingSignal17KnowledgeProvider : _TtCs12_SwiftObject

@end
