/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriAudioSupport.framework/SiriAudioSupport
 */

@interface SiriAudioSupport.NowPlayingAppEngagementSignal : _TtCs12_SwiftObject

@end
