/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKElementWrapper : NSObject {
    REElement * _element;
}

@property (nonatomic, retain) REElement *element;

- (void).cxx_destruct;
- (id)element;
- (unsigned long long)hash;
- (id)initWithElement:(id)arg1;
- (bool)isEqual:(id)arg1;
- (void)setElement:(id)arg1;

@end
