/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CoreKnowledge.RequestEntity : _TtCs12_SwiftObject {
    void entity;
    void matches;
}

@end
